# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a60d475eba9635c00312aa744146341fee7998090021088047f9db9b75586e88f0481daf6b3efe099b1b9a3f7db7520b51dbc6be4a5f0c08506dde0400311d3

test:
  secret_key_base: 064a2786bcd695d549498a9f197028724b0996730b55cbb5268837506a19a5fde8c52444d9d267515fdd8ed12cd8b6c8c5c50db8ed0b7b40a75dc59a8872f224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
